#pragma warning disable
using InventoryModule;
using InventoryModule.IDSystem.Instance;
using InventoryModule.Packer;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace InventoryModule
{
    /// <summary>
    /// Script that enables any scriptable object to become an inventoryItem.(ID for this item is autogenerated)
    /// </summary>

    public abstract class ItemScriptableObject : ScriptableObject, IItem
    {
        [SerializeField, HideInInspector] private uint itemId;
        [SerializeField] private int maxAmount;
        [SerializeField] private Sprite icon;
        public uint ItemId => itemId;

        public int MaxAmount => maxAmount;

        public Sprite Icon => icon;

        //expicit to prevent external for rewriting 
        void IItem.SetID(uint id)
        {
            itemId = id;
        }
    }

    /// <summary>
    /// This class makes this Item type of Instance
    /// </summary>
    public abstract class InstanceItemScriptableObject : ScriptableObject, IInstanceable, IInstanceDataPacker , IGetType
    {
        [SerializeField, HideInInspector] private uint itemId = 0;
        [SerializeField] private int maxAmount;
        [SerializeField] private Sprite icon;
        [SerializeField] private uint test;

        private ulong instanceID = 0;
        public uint ItemId => itemId == 0 ? 0 : itemId;

        public int MaxAmount => maxAmount;

        public Sprite Icon => icon;

        public ulong InstanceId { get => instanceID; set => instanceID = value; }



        private void Awake()
        {
            //Safety feature to prevent Editor form Writing
            if (!Application.isPlaying)
                return;

            if (instanceID == 0)
                instanceID = InstanceIDHandler.GenerateID();
            InstanceDataWriter.Instance.BeginWritingFor(this);



            Debug.Log($"{itemId}, {instanceID}");
        }

        //expicit to prevent external for rewriting 
        void IItem.SetID(uint id)
        {
            itemId = id;
            test = id;
        }

        

        public abstract void WriteDataToPacker(InstanceDataWriter writer);
        public abstract void ReadDataFormPacker(InstanceDataReader reader);

        public object GetobjectRef()
        {
            return this;
        }
    }
}
