#pragma warning disable
using InventoryModule;
using InventoryModule.IDSystem.Instance;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace InventoryModule.IDSystem
{
    /// <summary>
    /// Script that enables any scriptable object to become an inventoryItem.(ID for this item is autogenerated)
    /// </summary>

    public abstract class ItemScriptableObject : ScriptableObject, IItem
    {
        [SerializeField, HideInInspector] private uint? itemId = null;
        public uint? ItemID => itemId;

        public abstract int MaxAmount { get; }

        public abstract Sprite Icon { get; }

        //expicit to prevent external for rewriting 
        void IItem.SetID(uint id)
        {
            itemId = id;
        }
    }

    public abstract class InstanceItemScriptableObject : ScriptableObject, IItem , IInstanceID
    {
        [SerializeField, HideInInspector] private uint? itemId = null;
        [SerializeField, HideInInspector] private ulong? instanceID = null;
        public uint? ItemID => itemId;

        public abstract int MaxAmount { get; }

        public abstract Sprite Icon { get; }
        public ulong? InstanceID { get => instanceID.Value; set => instanceID = InstanceIDHandler.GenerateID(); }

        //expicit to prevent anything expect id system form calling it.
        void IItem.SetID(uint id)
        {
            itemId = id;
        }     
    }
}
