#pragma warning disable
using InventoryModule;
using InventoryModule.IDSystem.Instance;
using InventoryModule.Packer;
using NUnit.Framework;
using NUnit.Framework.Internal.Execution;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace InventoryModule
{
    /// <summary>
    /// Script that enables any scriptable object to become an inventoryItem.(ID for this item is autogenerated)
    /// </summary>

    public abstract class ItemScriptableObject : ScriptableObject, IItem
    {
        [SerializeField, HideInInspector] private uint itemId = 0;
        [SerializeField] private int maxAmount;
        [SerializeField] private Sprite icon;
        public uint ItemID => itemId;

        public int MaxAmount => maxAmount;

        public Sprite Icon => icon;

        //expicit to prevent external for rewriting 
        void IItem.SetID(uint id)
        {
            itemId = id;
        }
    }

    /// <summary>
    /// This class makes this Item type of Instance
    /// </summary>
    public abstract class InstanceItemScriptableObject : ScriptableObject, IInstanceable, IInstanceDataPacker
    {
        [SerializeField, HideInInspector] private uint itemId = 0;
        [SerializeField] private int maxAmount;
        [SerializeField] private Sprite icon;
        [SerializeField] private uint test;

         private ulong instanceID = 0;
        public uint ItemID => itemId == 0 ? 0 : itemId;

        public int MaxAmount => maxAmount;

        public Sprite Icon => icon;

        public ulong InstanceID { get => instanceID; set => instanceID = value; }

        public void ExecuteWrite()
        {
            if (InstanceDataServicePovider.S_instanceDataServicePovider.Begin(this))
            {
                Debug.Log("Writing for arrow");               
                    WriteDataToPacker(new InstanceDataWriter());
            }
        }

        public void ExecuteReader()
        {

        }

        private void Awake()
        {
            if (!Application.isPlaying)
                return;

            if (instanceID == 0)
                instanceID = InstanceIDHandler.GenerateID();
            ExecuteWrite();

            Debug.Log($"{itemId}, {instanceID}");
        }

        //expicit to prevent external for rewriting 
        void IItem.SetID(uint id)
        {
            itemId = id;
            test = id;
        }

        public abstract void WriteDataToPacker(InstanceDataWriter writer);
        public abstract void ReadDataFormPacker(InstanceDataReader reader);
    }
}
