#pragma warning disable
using InventoryModule;
using InventoryModule.IDSystem.Instance;
using NUnit.Framework;
using NUnit.Framework.Internal.Execution;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace InventoryModule
{
    /// <summary>
    /// Script that enables any scriptable object to become an inventoryItem.(ID for this item is autogenerated)
    /// </summary>

    public abstract class ItemScriptableObject : ScriptableObject, IItem
    {
        [SerializeField, HideInInspector] private uint? itemId = null;
        [SerializeField] private int maxAmount;
        [SerializeField] private Sprite icon;
        public uint? ItemID => itemId;

        public int MaxAmount => maxAmount;

        public Sprite Icon => icon;

        //expicit to prevent external for rewriting 
        void IItem.SetID(uint id)
        {
            itemId = id;
        }
    }

    /// <summary>
    /// This class makes this Item type of Instance
    /// </summary>
    public abstract class InstanceItemScriptableObject : ScriptableObject, IItem, IInstanceable
    {
        [SerializeField] private uint itemId;
        [SerializeField, HideInInspector] private ulong? instanceID = null;
        [SerializeField] private int maxAmount;
        [SerializeField] private Sprite icon;
        [SerializeField] private uint test;

        public uint? ItemID => itemId == 0 ? null : itemId ;

        public int MaxAmount => maxAmount;

        public Sprite Icon => icon;

        public ulong? InstanceID { get => instanceID; set => instanceID = value; }

        private void Awake()
        {
            if (!Application.isPlaying)
                return;

            if (!instanceID.HasValue)
                instanceID = InstanceIDHandler.GenerateID();

            Debug.Log($"ItemID: {(ItemID.HasValue ? ItemID.Value.ToString() : "NULL")} | InstanceID: {instanceID}");
        }

        //expicit to prevent external for rewriting 
        void IItem.SetID(uint id)
        {
            itemId = id;
            test = id;
        }
    }
}
