#pragma warning disable
using InventoryModule;
using System;
using UnityEngine;

namespace InventoryModule.IDSystem
{
    /// <summary>
    /// Script that enables any scriptable object to become an inventoryItem.(ID for this item is autogenerated)
    /// </summary>

    public abstract class ItemScriptableObject : ScriptableObject, IItem
    {
        [SerializeField, HideInInspector] private uint? itemId = null;
        public uint? ItemID => itemId;

        public abstract int MaxAmount { get; }

        public abstract Sprite Icon { get; }

        //expicit to prevent external for rewriting 
        void IItem.SetID(uint id)
        {
            itemId = id;
        }
    }
}
