#pragma warning disable
using InventoryModule.Generics;
using System;
using UnityEngine;

namespace InventoryModule.IDSystem
{
    /// <summary>
    /// Script that enables any scriptable object to become an inventoryItem.(ID for this item is autogenerated)
    /// </summary>

    public abstract class ItemScriptableObject : ScriptableObject, IItemData
    {
        [SerializeField, HideInInspector] private uint? itemId = null;
        public  uint? ItemID => itemId;

        public abstract int MaxAmount { get; }

        public abstract Sprite Icon { get; }

        public virtual bool CanStackWith(IItemData other)
        {
            if(other == null) throw new ArgumentNullException(other.ItemID + "is null");

            return other.ItemID == itemId;
        }

        //expicit to prevent external for rewriting 
        void IItemData.SetID(uint id)
        {
            itemId = id;
        }
    }
}
