#pragma warning disable CS102
using InventoryModule.Generics.Interfaces;
using UnityEngine;

namespace InventoryModule
{
    /// <summary>
    /// Script that enables any scriptable object to become an inventoryItem.(ID for this item is autogenerated)
    /// </summary>

    public abstract class ItemScritableObject : ScriptableObject, IItemData
    {
        [SerializeField, HideInInspector] private int Itemid;
        public int ItemID => Itemid;
        public abstract int MaxAmount { get; }

        public abstract Sprite Icon { get; }

        public bool CanStackWith(IItemData other)
        {
            return ItemID == other.ItemID;
        }
        public void SetID(int id)
        {
            Itemid = id;
        }
    }
}
